starwave/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
import waveapp.urls as wave_urls

urlpatterns = [
    path("", include(wave_urls)),
    path("accounts/", include("django.contrib.auth.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

waveapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("profile/<slug:username>", views.profile, name="profile"),
    path("passwords/change", views.change_password, name="change_password"),
    path("employees/add", views.new_employee, name="new_employee"),
    path("employees/delete", views.delete_employee, name="delete_employee"),
    path("loans", views.loans, name="loans"),
    path("loans/new", views.new_loan, name="new_loan"),
    path("loans/<slug:loan_id>", views.loan, name="loan"),
    path("loan/pay", views.pay_loan, name="pay_loan"),
    path("loan/paid", views.paid_loans, name="paid_loans"),
    path("loan/defaults", views.defaulted_loans, name="defaulted_loans"),
    path("loan/defaults/new", views.default_loan, name="default_loan"),
    path("loan/extend", views.extend_loan, name="extend_loan"),
    path("collaterals", views.collaterals, name="collaterals"),
    path("collateral/collected", views.collected_collaterals, name="collected_collaterals"),
    path("collateral/confiscated", views.confiscated_collaterals, name="confiscated_collaterals"),
    path("collaterals/<slug:id>", views.collateral_details, name="collateral"),
    path("reports", views.reports, name="reports"),
    path("activity/log", views.activity_log, name="activity_log"),
]

waveapp/models.py
from datetime import timedelta

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.contrib.auth.models import User

loan_statuses = (
    ("Paid", "Paid"),
    ("Unpaid", "Unpaid"),
)

collaterals_statuses = (
    ("Collected", "Collected"),
    ("Not Collected", "Not Collected"),
)

activity_types = (
    ("New Loan", "New Loan"),
    ("Loan Repayment", "Loan Repayment"),
    ("Loan Extension", "Loan Extension"),
    ("Loan Defaulted", "Loan Defaulted")
)


class Loans(models.Model):
    loan_id = models.CharField(max_length=100, unique=True, blank=True, null=False)
    client_name = models.CharField(max_length=300, null=False)
    client_id_no = models.CharField(max_length=10, null=False)
    client_phone_no = models.CharField(max_length=10, null=False)
    collateral_name = models.CharField(max_length=200, null=False)
    issue_date = models.DateTimeField(default=timezone.now)
    loan_period = models.IntegerField(default=7)
    repayment_date = models.DateTimeField(default=(timezone.now() + timedelta(days=7)))
    loan_amount = models.FloatField()
    interest_rate = models.FloatField(default=0.3)
    repayment_amount = models.FloatField()
    loan_status = models.CharField(max_length=100, choices=loan_statuses)
    issued_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="Users")
    created_on = models.DateTimeField(default=timezone.now)
    paid_on = models.DateTimeField(default=timezone.now, null=True)
    collateral_id = models.CharField(max_length=100, unique=True, blank=True, null=False)
    default_status = models.BooleanField(default=False)
    defaulted_on = models.DateTimeField(default=timezone.now)
    overdue = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    paid_amount = models.FloatField(null=True)
    remaining_amount = models.FloatField(null=True)
    loan_extended = models.BooleanField(default=False)
    loan_extensions = models.IntegerField(default=0)
    extended_on = ArrayField(models.DateTimeField(default=timezone.now), null=True)

    def __str__(self):
        return self.client_id_no

    class Meta:
        get_latest_by = ['created_on']


class Collaterals(models.Model):
    collateral_id = models.CharField(max_length=100, unique=True, blank=True, null=False)
    collateral_name = models.CharField(max_length=200, null=False)
    loan = models.OneToOneField(Loans, on_delete=models.CASCADE)
    held_on = models.DateTimeField(default=timezone.now)
    collection_date = models.DateTimeField(default=timezone.now)
    collected_on = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=100, choices=collaterals_statuses)
    confiscated = models.BooleanField(default=False)
    confiscated_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.collateral_name

    class Meta:
        get_latest_by = ['held_on']


@receiver(post_save, sender=Loans)
def create_collateral(sender, instance, created, **kwargs):
    if created:
        collateral = Collaterals.objects.create(
            loan=instance,
            collateral_name=instance.collateral_name,
            collateral_id=instance.collateral_id,
            held_on=instance.created_on,
            collection_date=instance.repayment_date,
            status="Not Collected"
        )
        collateral.save()


class Activities(models.Model):
    type = models.CharField(max_length=100, choices=activity_types)
    initiator = models.ForeignKey(User, on_delete=models.CASCADE)
    initiated_on = models.DateTimeField(default=timezone.now)
    loan = models.ForeignKey(Loans, on_delete=models.CASCADE)

    def __str__(self):
        return self.type + " - " + self.loan.loan_id

templates/activity_log.html
{% extends 'base.html'%}
{%load static%}
{%load humanize%}
{%block styles%}
{%endblock styles%}
{%block content%}
<!-- Main Content -->
<div id="content">
    {%include 'navbar.html'%}
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Activity Log</h1>
        </div>
        <p>A list of all activities performed by all users of this system.</p>
      <hr>
        <div class="card border-0 mb-4 bg-light">
            <div class="card-body px-0">
                <div class="table-responsive">
                    <table class="table table-striped table-borderless" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Activity</th>
                            <th>Initiator</th>
                            <th>Date</th>
                        </tr>
                        </thead>
                        <tbody class="mb-4">
                        {%if activities%}
                        {%for act in activities%}
                        <tr>
                            <td><a href="{%url 'loan' loan_id=act.loan.loan_id%}">{{act}}</a></td>
                            <td>{{act.initiator}}</td>
                            <td>{{act.initiated_on|naturaltime}}</td>
                        </tr>
                        {%endfor%}
                        {%endif%}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->
{%endblock content%}
{%block scripts%}
{%endblock scripts%}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Starwave - Dashboard</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

    {%block styles%}
    {%endblock styles%}

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{%url 'dashboard'%}">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-star"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Starwave</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item {%if request.path == '/'%} active{%endif%}">
            <a class="nav-link" href="{%url 'dashboard'%}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>


        <!-- Nav Item - Loans-->
        <li class="nav-item {%if 'loans' in request.path%} active{%endif%}">
            <a class="nav-link collapsed" href="{%url 'loans'%}"
               aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-money-check-alt"></i>
                <span>Loans</span>
            </a>
        </li>

        <!-- Nav Item - Collateral -->
        <li class="nav-item {%if 'collaterals' in request.path%} active{%endif%}">
            <a class="nav-link collapsed" href="{%url 'collaterals'%}"
               aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fas fa-fw fa-list"></i>
                <span>Collaterals</span>
            </a>
        </li>

        <!-- Nav Item - Reports -->
        <li class="nav-item {%if 'reports' in request.path%} active{%endif%}">
            <a class="nav-link" href="{%url 'reports'%}">
                <i class="fas fa-fw fa-file"></i>
                <span>Reports</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>


    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        {%block content%}
        {%endblock content%}

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Built by Clinton</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer d-flex justify-content-between">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{% url 'logout'%}">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

<!-- Page level plugins -->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{%block scripts%}
{%endblock scripts%}
<script>
window.onload = function() {
    if ($(window).width() < 560 && !$(".sidebar").hasClass("toggled")) {
      $("body").addClass("sidebar-toggled");
      $(".sidebar").addClass("toggled");
      $('.sidebar .collapse').collapse('hide');
    };
};
</script>
</body>

</html>

templates/collateral.html
{% extends 'base.html'%}
{%load static%}
{%load humanize%}
{%load to_percent%}
{%block styles%}
{%endblock styles%}
{%block content%}
<!-- Main Content -->
<div id="content">
    {%include 'navbar.html'%}
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Collateral Details</h1>

        </div>
        <p>These are the details of the collateral item with ID {{col.collateral_id}}.</p>
        <hr>
        <div class="row py-0">
            <div class="col-sm-6 ">
                <div class="card-body p-1">
                    <div class="row no-gutters align-items-center">
                        <span class="h6 font-weight-bold">Collateral ID:<span
                                class="text-primary"> {{col.collateral_id}}</span></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 ">
                <div class="card-body p-1">
                    <div class="row no-gutters align-items-center">
                        <span class="h6 font-weight-bold">Collateral Name:<span class="text-primary"> {{col.collateral_name}}</span></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 ">
                <div class="card-body p-1">
                    <div class="row no-gutters align-items-center">
                        <span class="h6 font-weight-bold">Loan Associated:<span
                                class="text-primary"> <a href="{%url 'loan' loan_id=col.loan.loan_id%}">Details <i
                                class="fas fa-arrow-right"></i></a> </span></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 ">
                <div class="card-body p-1">
                    <div class="row no-gutters align-items-center">
                        <span class="h6 font-weight-bold">Held On:<span class="text-primary"> {{col.held_on|naturalday}}</span></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 ">
                <div class="card-body p-1">
                    <div class="row no-gutters align-items-center">
                        <span class="h6 font-weight-bold">To Be Collected On:<span class="text-primary"> {{col.collection_date|naturalday}}</span></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 ">
                <div class="card-body p-1">
                    <div class="row no-gutters align-items-center">
                        <span class="h6 font-weight-bold">Collection Status:<span class="text-primary"> {{col.status}}</span></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 ">
                <div class="card-body p-1">
                    <div class="row no-gutters align-items-center">
                        <span class="h6 font-weight-bold">Confiscated?:<span class="text-primary"> {{col.confiscated}}</span></span>
                    </div>
                </div>
            </div>

        </div>


    </div>
    <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->
{%endblock content%}
{%block scripts%}
{%endblock scripts%}

templates/collaterals.html
{% extends 'base.html'%}
{%load static%}
{% load humanize %}
{%block styles%}
{%endblock styles%}
{%block content%}
<!-- Main Content -->
<div id="content">
    {%include 'navbar.html'%}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">List of Active Collaterals</h1>
        </div>
        <p>This is a list of all the active collaterals held by Starwave Electronics awaiting clients to repay their loans. You can search or filter for a specific item. Click on the name of the collateral to view its details. Go to <a href="{%url 'reports'%}#inactive-loans" >Reports</a> to view all collected items.</p>
        <hr>
        <div class="card border-0 mb-4 bg-light px-0 mx-0">
            <div class="card-body px-0">
                <div class="table-responsive">
                    <table class="table table-striped table-borderless" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Collateral Name</th>
                            <th>Client Name</th>
                            <th>Phone Number</th>
                        </tr>
                        </thead>
                        <tbody class="mb-4">
                        {%if collaterals%}
                        {%for col in collaterals%}
                        <tr>
                            <td><a href="{%url 'collateral' id=col.collateral_id%}">{{col.collateral_name}}</a></td>
                            <td>{{col.loan.client_name}}</td>
                            <td>{{col.loan.client_phone_no}}</td>
                        </tr>
                        {%endfor%}
                        {%endif%}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->

</div>
<!-- New Loan Modal-->
<div class="modal fade" id="newLoanModal" tabindex="-1" role="dialog"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary">New Loan</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="text-danger">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="user" id="new-loan-form" method="post">
                    {%csrf_token%}
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" name="client_name"
                               placeholder="Full Names" maxlength="300" required="" id="id_client_name">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user"
                               placeholder="ID Number" name="client_id_no" maxlength="10" required=""
                               id="id_client_id_no">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user"
                               placeholder="Phone Number" name="client_phone_no" maxlength="10" required=""
                               id="id_client_phone_no">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user"
                               placeholder="Collateral Name" name="collateral_name" maxlength="200" required=""
                               id="id_collateral_name">
                    </div>
                    <div class="form-group">
                        <input type="number" class="form-control form-control-user"
                               placeholder="Loan Period (days)" name="loan_period" required="" id="id_loan_period">
                    </div>
                    <div class="form-group">
                        <input type="number" class="form-control form-control-user"
                               placeholder="Loan Amount" name="loan_amount" step="any" required="" id="id_loan_amount">
                    </div>
                    <div class="form-group mt-4">
                        <button type="submit" class="btn btn-primary btn-user btn-block" id="create-loan">
                            Create
                        </button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<!-- End of Main Content -->
{%endblock content%}
{%block scripts%}
<script>
$("#new-loan-form").submit(function(e){
    $.ajax({
        url : "{% url 'new_loan' %}",
        type : "POST",
        data : {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            full_names: $("#id_client_name").val(),
            id_number: $("#id_client_id_no").val(),
            phone_number:$("#id_client_phone_no").val(),
            collateral_name:$("#id_collateral_name").val(),
            loan_period:$("#id_loan_period").val(),
            loan_amount:$("#id_loan_amount").val(),
        },
        dataType: "json",
        encode: true,
        }).done(function(response) {
            console.log(response);
            $('#newLoanModal').modal('hide');
            window.location.reload(true);
    });
    e.preventDefault();
});

</script>
{%endblock scripts%}

templates/collected_collaterals.html
{% extends 'base.html'%}
{%load static%}
{% load humanize %}
{%block styles%}
{%endblock styles%}
{%block content%}
<!-- Main Content -->
<div id="content">
    {%include 'navbar.html'%}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">List of All Collected Collaterals</h1>
        </div>
        <p>This is a list of all the collected collaterals once held by Starwave Electronics awaiting clients to repay their loans. You can search or filter for a specific item. Click on the name of the collateral to view its details.</p>
        <hr>
        <div class="card border-0 mb-4 bg-light px-0 mx-0">
            <div class="card-body px-0">
                <div class="table-responsive">
                    <table class="table table-striped table-borderless" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Collateral Name</th>
                            <th>Client Name</th>
                            <th>Phone Number</th>
                        </tr>
                        </thead>
                        <tbody class="mb-4">
                        {%if collaterals%}
                        {%for col in collaterals%}
                        <tr>
                            <td><a href="{%url 'collateral' id=col.collateral_id%}">{{col.collateral_name}}</a></td>
                            <td>{{col.loan.client_name}}</td>
                            <td>{{col.loan.client_phone_no}}</td>
                        </tr>
                        {%endfor%}
                        {%endif%}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->

</div>

<!-- End of Main Content -->
{%endblock content%}
{%block scripts%}
<script>

</script>
{%endblock scripts%}

templates/loans.html
{% extends 'base.html'%}
{%load static%}
{% load humanize %}
{%block styles%}
{%endblock styles%}
{%block content%}
<!-- Main Content -->
<div id="content">
    {%include 'navbar.html'%}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">List of Active Loans</h1>
            <button class="d-sm-inline-block btn btn-sm btn-primary shadow-sm" data-toggle="modal"
                    data-target="#newLoanModal"><i
                    class="fas fa-plus fa-sm text-white-50"></i> New Loan
            </button>
        </div>
        <p>This is a list of all the active loans given out to clients. You can search or filter for a specific loan. Click on the name of the client to view loan details. Go to <a href="{%url 'reports'%}#inactive-loans" >Reports</a> to view all paid/inactive loans</p>
        <hr>
        <div class="card border-0 mb-4 bg-light">
            <div class="card-body px-0">
                <div class="table-responsive">
                    <table class="table table-striped table-borderless" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Client Name</th>
                            <th>Loan Amount</th>
                            <th>Overdue</th>
                        </tr>
                        </thead>
                        <tbody class="mb-4">
                        {%if loans%}
                        {%for loan in loans%}
                        <tr>
                            <td><a href="{%url 'loan' loan_id=loan.loan_id%}">{{loan.client_name}}</a></td>
                            <td>{{loan.loan_amount|floatformat:2}}</td>
                            <td>{{loan.overdue}}</td>
                        </tr>
                        {%endfor%}
                        {%endif%}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->

</div>
<!-- New Loan Modal-->
<div class="modal fade" id="newLoanModal" tabindex="-1" role="dialog"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary">New Loan</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="text-danger">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="user" id="new-loan-form" method="post">
                    {%csrf_token%}
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" name="client_name"
                               placeholder="Full Names" maxlength="300" required="" id="id_client_name">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user"
                               placeholder="ID Number" name="client_id_no" maxlength="10" required=""
                               id="id_client_id_no">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user"
                               placeholder="Phone Number" name="client_phone_no" maxlength="10" required=""
                               id="id_client_phone_no">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user"
                               placeholder="Collateral Name" name="collateral_name" maxlength="200" required=""
                               id="id_collateral_name">
                    </div>
                    <div class="form-group">
                        <input type="number" class="form-control form-control-user"
                               placeholder="Loan Period (days)" name="loan_period" required="" id="id_loan_period">
                    </div>
                    <div class="form-group">
                        <input type="number" class="form-control form-control-user"
                               placeholder="Loan Amount" name="loan_amount" step="any" required="" id="id_loan_amount">
                    </div>
                    <div class="form-group mt-4">
                        <button type="submit" class="btn btn-primary btn-user btn-block" id="create-loan">
                            Create
                        </button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<!-- End of Main Content -->
{%endblock content%}
{%block scripts%}
<script>
$("#new-loan-form").submit(function(e){
    $.ajax({
        url : "{% url 'new_loan' %}",
        type : "POST",
        data : {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            full_names: $("#id_client_name").val(),
            id_number: $("#id_client_id_no").val(),
            phone_number:$("#id_client_phone_no").val(),
            collateral_name:$("#id_collateral_name").val(),
            loan_period:$("#id_loan_period").val(),
            loan_amount:$("#id_loan_amount").val(),
        },
        dataType: "json",
        encode: true,
        }).done(function(response) {
            console.log(response);
            $('#newLoanModal').modal('hide');
            window.location.reload(true);
    });
    e.preventDefault();
});

</script>
{%endblock scripts%}